name: Github Pages 部署

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm install

      - name: Build
        run: npm run build

      # - name: Deploy to GitHub Pages
      #   uses: crazy-max/ghaction-github-pages@v3
      #   with:
      #     target_branch: gh-pages
      #     build_dir: public
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: 部署到 Github
        uses: JamesIves/github-pages-deploy-action@v4.4.2
        with:
          token: ${{ secrets.TOKEN }}
          repository-name: cunyu1943/weekly
          branch: reco
          folder: public
          commit-message: "${{ github.event.head_commit.message }}"
